### ISSUE TITLE
cookiecutter failed to install

### ISSUE THREAD

**Issue by mithraictemple** [mandeepbhutani/cookiecutter-pyqt5#1]
Can't install cookiecutter with this message.
----- Installing cookiecutter -----
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\python.exe returned an exit code of 1.
----- Failed to install cookiecutter -----
I'm new to VS, does anyone have a clue as to what's going on here.

Thank you.

**Comment by mandeep** [comment]
@mithraictemple I'm not sure where the problem lies. You may want to report this on the cookiecutter repo or to VS support.

**Comment by mithraictemple** [comment]
Thanks for the reply. I'll chase it with vs.
